export const mockPoliklinikData = [
  {
    id: 1,
    nama: "Poli Umum",
    hari_buka: "Senin-Sabtu",
    jam_buka: "08:00",
    jam_tutup: "15:00",
    dokter_penanggungjawab: "Dr. Ahmad Santoso",
    dokter_bertugas: "Dr. Ahmad Santoso",
    backup_dokter: "Dr. Sari Wijaya",
    is_open_today: true,
    status_buka: "Buka Normal",
    keterangan: "Melayani konsultasi umum dan pengobatan dasar",
    is_dokter_cuti: false,
    warna: "blue",
    icon: "👨‍⚕️",
    antrian_sekarang: 15,
    estimasi_tunggu: "25 menit",
    telepon: "(021) 1234-5678",
    lokasi: "Lantai 1, Gedung A"
  },
  {
    id: 2,
    nama: "Poli Gigi",
    hari_buka: "Senin-Jumat",
    jam_buka: "09:00",
    jam_tutup: "16:00",
    dokter_penanggungjawab: "Dr. Sari Wijaya",
    dokter_bertugas: "Dr. Sari Wijaya",
    backup_dokter: "Dr. Budi Pratama",
    is_open_today: true,
    status_buka: "Buka Normal",
    keterangan: "Perawatan gigi dan mulut, perlu appointment",
    is_dokter_cuti: false,
    warna: "green",
    icon: "🦷",
    antrian_sekarang: 8,
    estimasi_tunggu: "15 menit",
    telepon: "(021) 1234-5679",
    lokasi: "Lantai 2, Gedung A"
  },
  {
    id: 3,
    nama: "Poli Jantung",
    hari_buka: "Senin-Kamis",
    jam_buka: "08:30",
    jam_tutup: "14:00",
    dokter_penanggungjawab: "Dr. Budi Pratama",
    dokter_bertugas: "Dr. Anita Sari (Pengganti)",
    backup_dokter: "Dr. Rina Melati",
    is_open_today: true,
    status_buka: "Buka dengan Dokter Backup",
    keterangan: "Khusus rujukan, dokter utama cuti",
    is_dokter_cuti: true,
    warna: "red",
    icon: "❤️",
    antrian_sekarang: 5,
    estimasi_tunggu: "40 menit",
    telepon: "(021) 1234-5680",
    lokasi: "Lantai 3, Gedung B"
  },
  {
    id: 4,
    nama: "Poli Anak",
    hari_buka: "Senin-Sabtu",
    jam_buka: "08:00",
    jam_tutup: "14:00",
    dokter_penanggungjawab: "Dr. Rina Melati",
    dokter_bertugas: "Dr. Rina Melati",
    backup_dokter: "Dr. Ahmad Santoso",
    is_open_today: false,
    status_buka: "Tutup",
    keterangan: "Buka besok pukul 08:00",
    is_dokter_cuti: false,
    warna: "yellow",
    icon: "👶",
    antrian_sekarang: 0,
    estimasi_tunggu: "-",
    telepon: "(021) 1234-5681",
    lokasi: "Lantai 1, Gedung B"
  },
  {
    id: 5,
    nama: "Poli Kandungan",
    hari_buka: "Senin-Jumat",
    jam_buka: "08:00",
    jam_tutup: "16:00",
    dokter_penanggungjawab: "Dr. Maya Sari",
    dokter_bertugas: "Dr. Maya Sari",
    backup_dokter: "Dr. Dian Utami",
    is_open_today: true,
    status_buka: "Buka Normal",
    keterangan: "Konsultasi kehamilan dan persalinan",
    is_dokter_cuti: false,
    warna: "pink",
    icon: "🤰",
    antrian_sekarang: 12,
    estimasi_tunggu: "30 menit",
    telepon: "(021) 1234-5682",
    lokasi: "Lantai 2, Gedung B"
  },
  {
    id: 6,
    nama: "Poli Bedah",
    hari_buka: "Senin, Rabu, Jumat",
    jam_buka: "09:00",
    jam_tutup: "15:00",
    dokter_penanggungjawab: "Dr. Hendra Wijaya",
    dokter_bertugas: "Dr. Hendra Wijaya",
    backup_dokter: "Dr. Andi Pratama",
    is_open_today: false,
    status_buka: "Tutup",
    keterangan: "Buka Rabu pukul 09:00",
    is_dokter_cuti: false,
    warna: "purple",
    icon: "🔪",
    antrian_sekarang: 0,
    estimasi_tunggu: "-",
    telepon: "(021) 1234-5683",
    lokasi: "Lantai 3, Gedung A"
  }
];

export const mockDoctorsData = [
  {
    id: 1,
    nama: "Dr. Ahmad Santoso",
    spesialisasi: "Dokter Umum",
    pengalaman: "10 tahun",
    pendidikan: "Spesialis Penyakit Dalam",
    foto: "/doctors/dr-ahmad.jpg",
    poliklinik: "Poli Umum",
    jadwal: "Senin-Sabtu, 08:00-15:00",
    telepon: "(021) 1234-5678",
    email: "ahmad.santoso@rumahsehat.com",
    bio: "Spesialis penyakit dalam dengan pengalaman 10 tahun dalam menangani berbagai kasus medis."
  },
  // ... tambahkan data dokter lainnya
];

export const mockAppointments = [];